---
- name: Tomcat. Install need packages
  yum:
    update_cache: yes
    name: "{{ yum_packages }}"
    state: latest



- name: Tomcat. Set firewall an Centos
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled

- name: Tomcat. Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Tomcat. Restart firewall on Centos
  shell: firewall-cmd --reload

